FROM openjdk:8-jdk-alpine
ADD target/hackatrix-back-spring-0.0.1-SNAPSHOT.jar hackatrix-back-spring-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/hackatrix-back-spring-0.0.1-SNAPSHOT.jar"]